const tags = [
    "Array",
    "String",
    "Hash Table",
    "Dynamic Programming",
    "Math",
    "Sorting",
    "Greedy",
    "Depth-First Search",
    "Database",
    "Binary Search",
    "Breadth-First Search",
    "Tree",
    "Matrix",
    "Two Pointers",
    "Binary Tree",
    "Bit Manipulation",
    "Heap (Priority Queue)",
    "Stack",
    "Graph",
    "Prefix Sum",
    "Simulation",
    "Design",
    "Backtracking",
    "Counting",
    "Sliding Window",
    "Union Find",
    "Linked List",
    "Ordered Set",
    "Enumeration",
    "Monotonic Stack",
    "Trie",
    "Recursion",
    "Divide and Conquer",
    "Bitmask",
    "Number Theory",
    "Queue",
    "Binary Search Tree",
    "Segment Tree",
    "Memoization",
    "Geometry",
    "Topological Sort",
    "Binary Indexed Tree",
    "Hash Function",
    "Game Theory",
    "Shortest Path",
    "Interactive",
    "Combinatorics",
    "Data Stream",
    "String Matching",
    "Rolling Hash",
    "Brainteaser",
    "Randomized",
    "Monotonic Queue",
    "Merge Sort",
    "Iterator",
    "Concurrency",
    "Doubly-Linked List",
    "Probability and Statistics",
    "Quickselect",
    "Bucket Sort",
    "Suffix Array",
    "Minimum Spanning Tree",
    "Counting Sort",
    "Shell",
    "Line Sweep",
    "Reservoir Sampling",
    "Eulerian Circuit",
    "Radix Sort",
    "Strongly Connected Component",
    "Rejection Sampling",
    "Biconnected Component"
];

const difficulty = [
    "Easy",
    "Medium",
    "Hard"
];

const status = [
    "Solved",
    "Attempted",
    "To Do"
];

export { tags, difficulty, status}


